version: '3.4'
services:
    frontend:
        build:
            context: ./frontend
        container_name: frontend
        command: npm run start -- -H 0.0.0.0
        ports:
            - 80:3000
