version: '3.4'
services:
    frontend:
        build:
            context: ./frontend
        container_name: frontend
        command: pm2-runtime npm -- start -- -H 0.0.0.0
        expose:
            - 3000

    nginx:
        build:
            context: ./nginx
        container_name: nginx
        depends_on:
            - frontend
        ports:
            - 80:80

networks:
    cgdb_frontend:
        driver: bridge
