from django.urls import path
from . import views

urlpatterns = [
    path('platforms/',
        views.PlatformPublicViewSet.as_view({'get': 'list'}),
        name='platform-list'),
    path('platforms/<slug:slug>/',
        views.PlatformPublicViewSet.as_view({'get': 'retrieve'}),
        name='platform-detail'),
    path('games/',
        views.FilteredGamesViewSet.as_view({'get': 'list'}),
        name='game-list'),
    path('games/<slug:slug>/',
        views.GamePublicViewSet.as_view({'get': 'retrieve'}),
        name='game-detail'),
    path('game-genres/',
        views.GameGenresViewSet.as_view({'get': 'list'}),
        name='game-genre-list'),
    path('search/<str:term>/',
        views.GameSearchViewSet.as_view({'get': 'list'}),
        name='search'),
    # celery producer (client)
    path('producer/crawl/<str:platform>/<str:source>',
        views.crawl,
        name='producer-crawl'),
    # POST from bot
    path('bot/wikipedia/game/',
        views.WikipediaGameBot.as_view(),
        name='bot-wikipedia-game-post'),
    path('bot/wikipedia/stadia/game/',
        views.WikipediaStadiaGameBot.as_view(),
        name='bot-wikipedia-stadia-game-post'),
    path('bot/reddit/stadia/game/',
        views.RedditStadiaGameBot.as_view(),
        name='bot-stadia-game-post'),
    path('bot/reddit/stadia/gamepro/',
        views.RedditStadiaGameProBot.as_view(),
        name='bot-stadia-game-pro-post'),
    path('bot/reddit/stadia/gamestats/',
        views.RedditStadiaGameStatsBot.as_view(),
        name='bot-stadia-game-stats-post'),
    path('bot/steampowered/game/',
        views.SteampoweredGameBot.as_view(),
        name='bot-steampowered-game-post'),
    path('bot/steampowered/stadia/game/',
        views.SteampoweredStadiaGameBot.as_view(),
        name='bot-steampowered-stadia-game-post'),
    path('bot/metacritic/stadia/game/',
        views.MetacriticStadiaGameBot.as_view(),
        name='bot-metacritic-stadia-game-post'),
]
