# Generated by Django 3.1.3 on 2020-11-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudgames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='modes',
            field=models.ManyToManyField(blank=True, related_name='games', related_query_name='game', to='cloudgames.Mode'),
        ),
        migrations.AlterField(
            model_name='game',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='games', related_query_name='game', to='cloudgames.Series'),
        ),
    ]
