# Generated by Django 3.1.4 on 2020-12-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgdb_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='slug',
            field=models.SlugField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
