WIKIPEDIA_SEARCH_URL_FORMAT = 'https://www.wikipedia.org/search-redirect.php?family=wikipedia&language=en&search={urlencoded}&language=en&go=Go'
WIKIPEDIA_ARTICLE_URL_FORMAT = 'https://en.wikipedia.org/wiki/{underscored_title}'
WIKIPEDIA_LOCAL_TITLE_SPLIT_CHAR = '–'
API_SERVER_HOST = 'http://localhost'
API_SERVER_PORT = '8000'